### ISSUE TITLE
It says, "this build successfully completed 5 days ago".

### ISSUE THREAD

**Issue by laichiaheng** [saivert/ddb_misc_headerbar_GTK3#10]
![2016-01-08 15 29 42](https://cloud.githubusercontent.com/assets/9532105/12192798/d9960bc0-b61c-11e5-9dba-43d340e26ad5.png)

**Comment by saivert** [comment]
When Alexey Yakovenko releases DeaDBeeF version 0.7.0 I will be able to build binaries for this plugin.
This plugin requires 0.7.0 anyways and will not be compatible with earlier versions.
