### ISSUE TITLE
syntax error near unexpected token GTK_DEPS,

### ISSUE THREAD

**Issue by kinh-nguyen** [saivert/ddb_misc_headerbar_GTK3#12]
Can you take a look at this error when run `configure`? I'm on Ubuntu 16.04, gnome-shell 3.20
```
checking deadbeef/deadbeef.h usability... yes
checking deadbeef/deadbeef.h presence... yes
checking for deadbeef/deadbeef.h... yes
./configure: line 12312: syntax error near unexpected token `GTK_DEPS,'
./configure: line 12312: `PKG_CHECK_MODULES(GTK_DEPS, gtk+-3.0, , as_fn_error $? "gtk+-3.0 is required for this package" "$LINENO" 5)'
```

**Comment by saivert** [comment]
Have you installed the package libgtk-3-dev ?
I just spun up a Ubuntu 16.04 LTS VM and installed deadbeef-static, copied /opt/deadbeef/include/deadbeef directory to /usr/include and ran ./autogen.sh && ./configure && make without issue.
plugin is then located in src/.libs relative to source dir.

**Comment by kinh-nguyen** [comment]
Thanks for your response. I had all above but still the same error.

```
libgtk-3-dev is already the newest version (3.20.8-1ubuntu0~ppa1).
```

**Comment by saivert** [comment]
What version of automake do you use?
What arguments to ./configure do you use? Environment variables?
I have automake-1.15 Package Version: 1:1.15-4ubuntu1

Also make sure there are no corruption in the source repository. Try a clean clone.
