### ISSUE TITLE
Icons are not visible

### ISSUE THREAD

**Issue by wvxwxvw** [saivert/ddb_misc_headerbar_GTK3#16]
On Windows 7, it looks like this.
![2022 01 13_201347](https://user-images.githubusercontent.com/13194155/149377566-968e677a-49f6-4b77-a02c-8fa5587aebf7.png)
Please correct if possible.

**Comment by saivert** [comment]
This looks like an issue with the icon loading in Deadbeef. We are investigating the issue together.

**Comment by kuba160** [comment]
Will be fixed in https://github.com/DeaDBeeF-Player/deadbeef/pull/2728
