### ISSUE TITLE
DeaDBeeF icon is tiny in headerbar

### ISSUE THREAD

**Issue by garuffalo** [saivert/ddb_misc_headerbar_GTK3#17]
Compared to the other icons, the DeaDBeeF icon is very small, compared to the other icons. Not a deal breaker, but it would be nice, visually, if the icon was larger.
If it is relevant, my screen resolution is 2560 x 1440.

Using Linux Mint 21.3 Cinnamon.
Dell E7470 Latitude

I would be receptive to a workaround if an actual fix is problematic.

![deadbeef_icon_headerbar](https://github.com/saivert/ddb_misc_headerbar_GTK3/assets/28717740/c0812751-0889-43e3-b4e7-c0eb023ceda9)

**Comment by saivert** [comment]
Are you using the build of deadbeef from the official site? It happens to be compiled incorrectly. This icon should not show at all, it was deprecated by GNOME a long time ago (Their App menus didn't work out). It doesn't contain anything not already accessible from other buttons/menus in Deadbeef UI.

Or if this is indeed a distro package then contact the package maintainer to make sure the correct build flags are applied.

To be clear. This icon is not added by this plugin but is part of the standard user interface of GTK.


EDIT: Deadbeef from the official site is built with GTK 3.10 but the feature that removes the App icon in the titlebar/headerbar needs GTK 3.14 (it queries the desktop environment whether it should display this or not.)

**Comment by garuffalo** [comment]
Thank you for the reply, and your excellent explanation. Yes, I am using the package from the official site.

I was wondering why some functions in the menu icon were redundant. The icon is a pleasing visual touch, in my opinion, and would still be nice if that's all it was. But I understand what you are saying.

The small size of the icon is just a niggle, and nothing much to worry about. Just figured I'd report it.
