### ISSUE TITLE
Headerbar shuffle button setting not persistent

### ISSUE THREAD

**Issue by garuffalo** [saivert/ddb_misc_headerbar_GTK3#18]
No matter what shuffle setting I choose from the headerbar shuffle button, it always reverts to "off" when I start DeaDBeeF. The shuffle behavior remains the same as the last session before start-up, and the built in DeaDBeeF menu (Playback > Shuffle) setting is unchanged, but the headerbar shuffle setting always goes back to "off".

While DeaDBeeF is open, the shuffle setting can be set properly in either the built in menu or the headerbar button, each one mirroring the other when the setting is changed.

I could just use the built in menu, but I like to keep that hidden (with a keyboard shortcut toggle). Would prefer the headerbar button.

Linux Mint 21.3 Cinnamon
Dell E7470 Latitude

![db_headerbar_shuffle](https://github.com/saivert/ddb_misc_headerbar_GTK3/assets/28717740/114bf1b2-a8aa-4c77-9176-d14e52fac2d0)

**Comment by saivert** [comment]
I just fixed shuffle and repeat so they are initialized to current state on startup.

**Comment by garuffalo** [comment]
Thank you very much for addressing this. I love the headerbar plugin. It really provides a beautiful, slick interface for DeaDBeeF!
