### ISSUE TITLE
I have a stupid question.

### ISSUE THREAD

**Issue by laichiaheng** [saivert/ddb_misc_headerbar_GTK3#5]
How do I install it?

**Comment by saivert** [comment]
Like so:
$ git clone https://github.com/saivert/ddb_misc_headerbar_GTK3.git
$ cd ddb_misc_headerbar_GTK3
$ ./autogen.sh
$ ./configure
$ make
$ cp src/.libs/ddb_misc_headerbar_GTK3.so ~/.local/lib/deadbeef

Or grab binary here:
https://saivert.com/files/ddb_misc_headerbar_GTK3-42ec541-x86_64.zip
https://saivert.com/files/ddb_misc_headerbar_GTK3-42ec541-i686.zip
and copy to your deadbeef plugins directory.

I have also updated the readme with link to these.
They are built using deadbeef-plugin-builder.

**Comment by laichiaheng** [comment]
Thanks!
