### ISSUE TITLE
There are 2 progress bar, and 2 control pannel.

### ISSUE THREAD

**Issue by laichiaheng** [saivert/ddb_misc_headerbar_GTK3#7]
![2015-12-30 11 53 53](https://cloud.githubusercontent.com/assets/9532105/12046129/215a34aa-aeec-11e5-9cd2-fcf7c01f1349.png)

**Comment by saivert** [comment]
Yes. You need to remove the built-in widgets by clicking menu button->View->Design Mode
Then right click on control panel (which is called playback controls) and click Delete. Do the same for the built-in progress bar.

**Comment by laichiaheng** [comment]
@saivert Thanks, problem solved.
