### ISSUE TITLE
The function key doesn't work for play/pause

### ISSUE THREAD

**Issue by laichiaheng** [saivert/ddb_misc_headerbar_GTK3#8]
It worked before, but doesn't work after installing the ddb_misc_headerbar_GTK3
![dsc_0227](https://cloud.githubusercontent.com/assets/9532105/12047369/41571174-af05-11e5-9393-e41243f5ae95.jpg)

**Comment by saivert** [comment]
I cannot reproduce.
Can you try uninstalling the plugin and see if mediakeys work again?
Also check the hotkey preferences. See if XF86MediaPlay is set up.
